runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /static
  static_dir: app/static
- url: /.*
  script: application.app
# [END handlers]

skip_files:
  - ^env$

libraries:
- name: numpy
  version: "1.6.1"